In [450]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import keras
from keras import layers

In [451]:
data = pd.read_csv("iris_data.csv")

In [452]:
data.head()

sepal_length  sepal_width  petal_length  petal_width       flower
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [453]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [454]:
print(y.shape)

(150,)


In [455]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [456]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [457]:
print(X[:, 3].max())

2.5


In [458]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [459]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, :] = sc.fit_transform(X_train[:, :])
X_test[:, :] = sc.transform(X_test[:, :])

In [460]:
print(X_train)

[[ 8.03473255e-01 -5.32605965e-01  4.54251771e-01  3.80020799e-01]
 [ 1.04344393e+00 -1.25712258e+00  1.13184820e+00  7.69310398e-01]
 [ 1.16342927e+00 -4.95948874e-02  9.62449091e-01  1.15860000e+00]
 [-8.76321497e-01  1.15793281e+00 -1.35267203e+00 -1.17713760e+00]
 [ 2.03546558e-01 -1.98163920e+00  6.80117246e-01  3.80020799e-01]
 [ 5.63502576e-01 -2.91100426e-01  1.01891546e+00  7.69310398e-01]
 [ 9.23458594e-01 -2.91100426e-01  4.54251771e-01  1.20494400e-01]
 [ 2.24329733e+00 -1.01561704e+00  1.75297825e+00  1.41812640e+00]
 [-1.56409460e-01  1.88244942e+00 -1.18327293e+00 -1.17713760e+00]
 [-9.96306836e-01  1.39943835e+00 -1.35267203e+00 -1.30690080e+00]
 [-1.23627752e+00 -4.95948874e-02 -1.35267203e+00 -1.17713760e+00]
 [-7.56336157e-01 -7.74111504e-01  5.89871889e-02  2.50257599e-01]
 [-8.76321497e-01  9.16427268e-01 -1.29620566e+00 -1.30690080e+00]
 [-3.96380139e-01  1.15793281e+00 -1.40913840e+00 -1.30690080e+00]
 [ 2.24329733e+00  1.88244942e+00  1.64004552e+00  1.28836320e

In [461]:
X_train.shape

(112, 4)

In [462]:
y_train.shape

(112,)

In [463]:
inputs_1 = keras.Input(shape=(4,), name="Iris Flower Features")
layer_1 = layers.Dense(32, activation="relu", name="dense_layer_1")(inputs_1)
layer_2 = layers.Dense(32, activation="relu", name="dense_layer_2")(layer_1)
outputs_1 = layers.Dense(3, activation="softmax", name="output_layer")(layer_2)

In [464]:
model = keras.Model(inputs=inputs_1, outputs=outputs_1, name="iris_model")

In [465]:
model.compile(
    optimizer=keras.optimizers.Adam(),
    loss=keras.losses.SparseCategoricalCrossentropy(),
    metrics=[keras.metrics.SparseCategoricalAccuracy()]
)

In [466]:
model.summary()

Model: "iris_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Iris Flower Features (Inpu  [(None, 4)]               0         
 tLayer)                                                         
                                                                 
 dense_layer_1 (Dense)       (None, 32)                160       
                                                                 
 dense_layer_2 (Dense)       (None, 32)                1056      
                                                                 
 output_layer (Dense)        (None, 3)                 99        
                                                                 
Total params: 1315 (5.14 KB)
Trainable params: 1315 (5.14 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [467]:
print("Fit the model on the training data")
history=model.fit(
    X_train,
    y_train,
    batch_size=32,
    epochs=100,
)

Fit the model on the training data
Epoch 1/100
4/4 [==============================] - 1s 5ms/step - loss: 1.0692 - sparse_categorical_accuracy: 0.4196
Epoch 2/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0091 - sparse_categorical_accuracy: 0.5268
Epoch 3/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9529 - sparse_categorical_accuracy: 0.5982
Epoch 4/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9026 - sparse_categorical_accuracy: 0.6696
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 0.8568 - sparse_categorical_accuracy: 0.7411
Epoch 6/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8111 - sparse_categorical_accuracy: 0.7679
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 0.7688 - sparse_categorical_accuracy: 0.7768
Epoch 8/100
4/4 [==============================] - 0s 4ms/step - loss: 0.7280 - sparse_categorical_accuracy: 0.7768
Epoch 9/100
4/4 [====================

In [468]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

2/2 [==============================] - 0s 12ms/step


In [469]:
test_scores = model.evaluate(X_test, y_test, verbose=2)
print("Test loss:", test_scores[0])
print("Test accuracy:", test_scores[1])

2/2 - 0s - loss: 0.0742 - sparse_categorical_accuracy: 0.9737 - 130ms/epoch - 65ms/step
Test loss: 0.07424193620681763
Test accuracy: 0.9736841917037964


In [470]:
from sklearn.metrics import accuracy_score, confusion_matrix
#cm = confusion_matrix(y_test, y_pred)
#acc = accuracy_score(y_test, y_pred)

In [471]:
print(cm, "\n", acc)

[[ 0 13  0]
 [ 0 16  0]
 [ 0  9  0]] 
 0.42105263157894735


In [472]:
history.history

{'loss': [1.0691890716552734,
  1.0091429948806763,
  0.9529035687446594,
  0.9026259779930115,
  0.8567857146263123,
  0.8110736012458801,
  0.7688270211219788,
  0.7280394434928894,
  0.6874478459358215,
  0.6487794518470764,
  0.6113678812980652,
  0.5775793790817261,
  0.5445592403411865,
  0.5147168040275574,
  0.4876019060611725,
  0.46241050958633423,
  0.4399625360965729,
  0.41865602135658264,
  0.399980753660202,
  0.38220903277397156,
  0.3652094900608063,
  0.35105109214782715,
  0.33651211857795715,
  0.324262410402298,
  0.310809850692749,
  0.29934218525886536,
  0.28838929533958435,
  0.27824148535728455,
  0.26879608631134033,
  0.25948768854141235,
  0.250887393951416,
  0.24273011088371277,
  0.23544715344905853,
  0.2274360954761505,
  0.2204979807138443,
  0.21428142488002777,
  0.20727451145648956,
  0.20151852071285248,
  0.19544151425361633,
  0.1898881196975708,
  0.18414516746997833,
  0.17875602841377258,
  0.17381569743156433,
  0.1685003936290741,
  0.16362