In [16]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [17]:
data = pd.read_csv("Social_Network_Ads.csv")

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [19]:
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [20]:
purchased_count_0, purchased_count_1 = data["Purchased"].value_counts()
purchased_0 = data[data["Purchased"] == 0]
purchased_1 = data[data["Purchased"] == 1]

In [21]:
print('class 0', purchased_0.shape)
print('class 1', purchased_1.shape)

class 0 (257, 3)
class 1 (143, 3)


In [22]:
print(purchased_count_0)
print(purchased_count_1)

257
143


In [23]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [24]:
from imblearn.over_sampling import SMOTE
from collections import Counter

smote = SMOTE()
X_smote, y_smote = smote.fit_resample(X, y)
print("Original dataset", Counter(y))
print("Resample dataset shape", Counter(y_smote))

Original dataset Counter({0: 257, 1: 143})
Resample dataset shape Counter({0: 257, 1: 257})


In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_smote, y_smote, test_size=0.25, random_state=1)

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [27]:
print(X_train)

[[-5.08611324e-01 -7.91376691e-01]
 [-8.84276283e-01  2.19079265e-01]
 [-1.35385748e+00  1.91769644e-01]
 [-4.14695085e-01 -6.00209348e-01]
 [-9.78192523e-01 -1.20102100e+00]
 [ 1.65146219e+00 -1.03047242e+00]
 [-3.90301256e-02 -8.18686312e-01]
 [ 1.08796475e+00  1.69379877e+00]
 [ 6.18383553e-01  2.73698506e-01]
 [-8.84276283e-01  9.58651096e-01]
 [-4.14695085e-01  8.25311626e-02]
 [ 9.00132272e-01 -1.20102100e+00]
 [ 6.18383553e-01 -1.41376294e+00]
 [-1.91735492e+00 -1.28294986e+00]
 [-1.25994124e+00 -1.00985365e+00]
 [ 1.36971347e+00  9.83748637e-01]
 [ 1.46362971e+00 -9.00615173e-01]
 [ 1.18188099e+00  1.14760636e+00]
 [ 1.48802354e-01 -5.45590107e-01]
 [ 8.06216032e-01 -1.00985365e+00]
 [-4.14695085e-01 -7.64067071e-01]
 [ 5.48861141e-02  8.25311626e-02]
 [-2.26862605e-01 -1.06447290e+00]
 [ 5.24467313e-01 -1.36487872e+00]
 [-6.96443804e-01 -1.47411720e+00]
 [-1.35385748e+00  4.10246608e-01]
 [-7.90360044e-01  1.72110839e+00]
 [-1.16602500e+00 -1.11909214e+00]
 [-1.32946365e-01 -2

In [28]:
print(X_test)

[[-1.16602500e+00 -4.90970867e-01]
 [ 1.27579723e+00  6.02301265e-04]
 [ 8.06216032e-01  1.88496611e+00]
 [-4.14695085e-01  5.19485090e-01]
 [-3.90301256e-02  2.08214157e+00]
 [-9.78192523e-01  2.07613345e+00]
 [ 1.93321091e+00  8.19890914e-01]
 [-1.07210876e+00 -1.09178252e+00]
 [ 1.74537843e+00 -1.33756910e+00]
 [-9.78192523e-01 -7.91376691e-01]
 [-3.20778845e-01 -5.45590107e-01]
 [ 5.48861141e-02  9.56439016e-01]
 [-3.90301256e-02 -2.67073192e-02]
 [ 1.48802354e-01 -1.14640176e+00]
 [ 1.18188099e+00  1.80303725e+00]
 [-1.54168996e+00  2.73698506e-01]
 [-1.63560620e+00  2.46388885e-01]
 [ 9.94048512e-01 -1.03716328e+00]
 [-3.20778845e-01  1.25684484e+00]
 [ 5.24467313e-01  1.91769644e-01]
 [-1.44777372e+00 -1.44680758e+00]
 [ 1.36971347e+00 -9.04820855e-01]
 [-4.14695085e-01  1.37150403e-01]
 [-3.90301256e-02  6.56033192e-01]
 [-1.16602500e+00  6.56033192e-01]
 [-6.96443804e-01  2.10879576e+00]
 [-6.96443804e-01  3.82936987e-01]
 [ 1.36971347e+00  8.50163380e-02]
 [ 7.12299792e-01  4

In [29]:
ann = tf.keras.models.Sequential()

In [30]:
ann.add(tf.keras.layers.Dense(units=4, activation="relu"))

In [31]:
ann.add(tf.keras.layers.Dense(units=4, activation="relu"))

In [32]:
ann.add(tf.keras.layers.Dense(units=4, activation="relu"))

In [33]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

In [34]:
ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy", "mse"])

In [35]:
ann.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
39/39 [==============================] - 2s 4ms/step - loss: 0.7227 - accuracy: 0.2234 - mse: 0.2647
Epoch 2/100
39/39 [==============================] - 0s 2ms/step - loss: 0.7029 - accuracy: 0.3013 - mse: 0.2549
Epoch 3/100
39/39 [==============================] - 0s 2ms/step - loss: 0.6933 - accuracy: 0.4494 - mse: 0.2501
Epoch 4/100
39/39 [==============================] - 0s 2ms/step - loss: 0.6878 - accuracy: 0.5247 - mse: 0.2473
Epoch 5/100
39/39 [==============================] - 0s 2ms/step - loss: 0.6816 - accuracy: 0.5247 - mse: 0.2443
Epoch 6/100
39/39 [==============================] - 0s 2ms/step - loss: 0.6683 - accuracy: 0.5766 - mse: 0.2376
Epoch 7/100
39/39 [==============================] - 0s 2ms/step - loss: 0.6387 - accuracy: 0.8208 - mse: 0.2230
Epoch 8/100
39/39 [==============================] - 0s 3ms/step - loss: 0.5976 - accuracy: 0.8727 - mse: 0.2032
Epoch 9/100
39/39 [==============================] - 0s 2ms/step - loss: 0.5492 - accuracy: 0.86

In [36]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.78)

5/5 [==============================] - 0s 2ms/step


In [37]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

In [38]:
print(cm)

[[51  4]
 [10 64]]


In [39]:
print(acc)

0.8914728682170543


In [43]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
print("Specificity: ", tn)
print("Sensitivity: ", tp)

Specificity:  51
Sensitivity:  64


In [44]:
from sklearn.metrics import classification_report
target = ["class 0", "class 1"]
print(classification_report(y_test, y_pred, target_names=target))

              precision    recall  f1-score   support

     class 0       0.84      0.93      0.88        55
     class 1       0.94      0.86      0.90        74

    accuracy                           0.89       129
   macro avg       0.89      0.90      0.89       129
weighted avg       0.90      0.89      0.89       129

